apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: samba-operator-proxy-rolebinding
  labels:
    {{- include "samba-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: samba-operator-proxy-role
subjects:
- kind: ServiceAccount
  name: samba-operator
  namespace: {{ .Release.Namespace }}

