apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: samba-operator-proxy-role
  labels:
    {{- include "samba-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create