apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba-operator-controller-manager
  labels:
    control-plane: controller-manager
    {{- include "samba-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      control-plane: controller-manager
      {{- include "samba-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        kubectl.kubernetes.io/default-logs-container: manager
      labels:
        control-plane: controller-manager
        {{- include "samba-operator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: samba-operator
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
      - name: kube-rbac-proxy
        args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
        resources: {}
        ports:
        - containerPort: 8443
          name: https
      - name: manager
        args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        command:
        - /manager
        env:
        - name: SAMBA_OP_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SAMBA_OP_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SAMBA_OP_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SAMBA_OP_WORKING_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: samba-operator-controller-cfg
        image: {{ .Values.manager.image.repository }}:{{ .Values.manager.image.tag }}
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
