# Default values for samba-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

manager:
  image:
    repository: quay.io/samba.org/samba-operator
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

serviceAccount:
  annotations: {}